### ISSUE TITLE
Errosディレクトリの名称変換がされない問題

### ISSUE THREAD

**Issue by katokaisya** [baserproject/BcAddonMigrator#6]
baserCMS 4系のテーマのエラー表示用のディレクトリ名
`Erros/`
を5系へのマイグレーション時に
`error/`
にリネームできるようにしたいです。

**Comment by ryuring** [comment]
@katokaisya こちらお願いしてもいいですか？

**Comment by ryuring** [comment]
@katokaisya あ、すでにプルリク作ってあるのですね。プルリク作る前提の場合は、Issueはいらないですよ。

**Comment by ryuring** [comment]
マージしましたのでクローズします。
